<?php
return [
    "bearer" => "AAAAAAAAAAAAAAAAAAAAALP1yAEAAAAAPqqB3c8vN1kQZbFLVYn7usWee54%3DYosNXx995ldmE4VJpBmCXgUoPDV2557zES3S14eQY4NjR3V2Kq",
    "access_token" => "1561687051006869508-yGKTsTc8mGxDMT30MILA8wVKAYPFo0",
    "access_secret_token" => "19IXm2P8ULwIP2eAyOV5HXzuutETN7gRLgcdFuQYE4mZF",
    "x-rapidapi-host" => "rocketapi-for-instagram.p.rapidapi.com",
    "x-rapidapi-key" => "a6f480bfa8msh5da5b8344d4c919p1a03dfjsn11c4d160c1cf",
    "api_url" => "https://rocketapi-for-instagram.p.rapidapi.com/instagram/",
    "user_info_endpoint" => "user/get_info",
    "user_info_by_id_endpoint" => 'user/get_info_by_id',
    "user_tags_endpoint" => 'user/get_tags',
    "user_tags_endpoint" => 'user/get_tags',
    "user_tags_endpoint" => 'user/get_tags',
    "user_followers_endpoint" => 'user/get_followers',
    "user_following_endpoint" => 'user/get_following',
    "user_stories_endpoint" => 'user/get_stories',
    'user_guides_endpoint' => 'user/get_guides',
    'user_highlights_endpoint' => 'user/get_highlights',
    'user_clips_endpoint' => 'user/get_clips',
    'user_live_endpoint' => 'user/get_live',
    'user_media_endpoint' => 'user/get_media',
    'user_similar_accounts_endpoint' => 'user/get_similar_accounts',
    'user_search_endpoint' => 'user/search',
    'media_info_endpoint' => 'media/get_info',
    'media_info_by_shortcode_endpoint' => 'media/get_info_by_shortcode',
    'media_likes_by_shortcode_endpoint' => 'media/get_likes',
    'media_comments_by_id_endpoint' => 'media/get_comments',
    'media_shortcode_by_id_endpoint' => 'media/get_shortcode_by_id',
    'media_id_by_shortcode_endpoint' => 'media/get_id_by_shortcode',
    'location_info_endpoint' => 'location/get_info',
    'location_media_endpoint' => 'location/get_media',
    'location_search_endpoint' => 'location/search',
    'hashtag_info_endpoint' => 'hashtag/get_info',
    'hashtag_media_endpoint' => 'hashtag/get_media',
    'hashtag_search_endpoint' => 'hashtag/search',
    'highlight_stories_endpoint' => 'highlight/get_stories',
    'comment_likes_endpoint' => 'comment/get_likes',
    'audio_media_endpoint' => 'audio/get_media',
    'audio_search_endpoint' => 'audio/search',
];

